App_Lakshabay/urls.py
from django.urls import path
from App_Lakshabay import views
app_name='App_Lakshabay'
urlpatterns = [
    path('',views.index,name='index'),
    path('menu/', views.MenuView, name='menus'),
    path('onlineorder/', views.onlineorder, name='onlineorder'),
    path('gifts/', views.GiftView, name='gifts'),
    path('book/', views.Bookview, name='book'),
    path('contact-us',views.ContactusView,name='contactus'),
    path('gallery/', views.GalleryView, name='gallery_image'),
]

App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name="cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),

    path('add-food/<pk>/', views.item_add_to_cart, name="item_ad"),
    path('item-cart/', views.item_cart_view, name="item_cart"),
    path('item-increase/<pk>/', views.itemincrease_cart, name="item_increase"),
    path('item-decrease/<pk>/', views.itemdecrease_cart, name="item_decrease"),
    path('item-remove/<pk>/', views.itemremove_from_cart, name="item_remove"),


]

lakshabay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Lakshabay.urls')),
    path('', include('App_Order.urls')),
    path('', include('App_Payment.urls')),
    path('superadmin/',include('App_Superadmin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

App_Lakshabay/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
# Create your models here.
class contact(models.Model):
    name = models.CharField(max_length=100, blank=False)
    email = models.EmailField(max_length=240, blank=False)
    phone = models.CharField(max_length=20, blank=False)
    message = models.TextField(max_length=300, blank=False)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return '{}-{}'.format(self.name, self.timestamp.date())




class gallery(models.Model):
    gallery_id = models.AutoField(primary_key=True)
    gallery_name = models.CharField(max_length=120, blank=True)
    image = models.ImageField(upload_to="images/", blank=True)

    def __str__(self):
        return self.gallery_name

    class Meta:
        verbose_name = _("Gallery")
        verbose_name_plural = _("Gallery")


class category(models.Model):
    category_id = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length=120, blank=False)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")


SELECT_GIFT_CAT_TYPE = (
    ('Voucher', 'Voucher'),
    ('Product', 'Product'),
)


class gift(models.Model):
    gift_id = models.AutoField(primary_key=True)
    gift_name = models.CharField(max_length=120, blank=False)
    gift_sl_no = models.CharField(max_length=120, blank=True)
    gift_category = models.ForeignKey(category, on_delete=models.CASCADE)
    gift_type = models.CharField(choices=SELECT_GIFT_CAT_TYPE, max_length=150)
    gift_meta = models.CharField(max_length=255, blank=False)
    gift_description = models.TextField()
    gift_image = models.ImageField(upload_to="gifts/", blank=False)
    gift_price = models.IntegerField(blank=True, null=True)
    gift_weight = models.IntegerField(blank=True, null=True)
    gift_dimension = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return self.gift_name


class menu_category(models.Model):
    menu_cat_id = models.AutoField(primary_key=True)
    menu_cat_name = models.CharField(max_length=120, blank=False)
    file=models.FileField(upload_to="Menuicon/",default="bell-pepper-capsicum.svg")

    def __str__(self):
        return self.menu_cat_name

    class Meta:
        verbose_name = _("Menu Category")
        verbose_name_plural = _("Menu Categories")


class Fitem(models.Model):
    item_id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=120, blank=False)
    item_category = models.ForeignKey(menu_category, on_delete=models.CASCADE)
    item_description = models.TextField()
    item_price = models.FloatField(blank=True, null=True)
    photo = models.ImageField(upload_to="Online Food", default='defaultfood.jpg')

    def __str__(self):
        return self.item_name


class book(models.Model):
    book_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=120, blank=False)
    last_name = models.CharField(max_length=120, blank=False)
    date = models.DateField(default=timezone.now)
    time = models.TimeField(null=True, blank=True, default=None)
    phone = models.CharField(max_length=13, blank=False)
    email = models.EmailField(max_length=120, blank=False)
    number_of_people = models.IntegerField(blank=True, null=True)
    message = models.TextField()

    def __str__(self):
        return str(self.book_id)

    class Meta:
        verbose_name = _("book")
        verbose_name_plural = _("book")


class menu(models.Model):
    menu_id = models.AutoField(primary_key=True)
    menu_name = models.CharField(max_length=120, blank=False)
    category = models.ForeignKey(menu_category, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.FloatField(blank=True, null=True)
    image = models.ImageField(upload_to="Menu/",default="defaultfood.jpg", blank=True)

    def __str__(self):
        return self.menu_name

App_Lakshabay/forms.py
from datetime import date
from django import forms
from App_Lakshabay.models import *
import re
from django.core.exceptions import ValidationError

CHOICES = (
    ('12:00 AM', '12:00 AM'),
    ('12:30 AM', '12:30 AM'),
    ('1:00 AM', '1:00 AM'),
    ('1:30 AM', '1:30 AM'),
    ('2:00 AM', '2:00 AM'),
    ('2:30 AM', '2:30 AM'),
    ('3:00 AM', '3:00 AM'),
    ('4:00 AM', '4:00 AM'),
    ('4:30 AM', '4:30 AM'),
    ('5:00 AM', '5:00 AM'),
    ('6:30 AM', '5:30 AM'),
    ('6:00 AM', '6:00 AM'),
    ('6:30 AM', '6:30 AM'),
    ('7:00 AM', '7:00 AM'),
    ('7:30 AM', '7:30 AM'),
    ('8:00 AM', '8:00 AM'),
    ('8:30 AM', '8:30 AM'),
    ('8:30 AM', '8:30 AM'),
    ('9:00 AM', '9:00 AM'),
    ('9:30 AM', '9:30 AM'),
    ('10:00 AM', '10:00 AM'),
    ('10:30 AM', '10:30 AM'),
    ('11:00 AM', '11:00 AM'),
    ('11:30 AM', '11:30 AM'),
    ('12:00 PM', '12:00 PM'),
    ('1:00 PM', '1:30 PM'),
    ('1:30 PM', '1:30 PM'),
    ('2:00 PM', '2:00 PM'),
    ('2:30 PM', '2:30 PM'),
    ('3:00 PM', '3:00 PM'),
    ('4:00 PM', '4:00 PM'),
    ('4:30 PM', '4:30 PM'),
    ('5:00 PM', '5:00 PM'),
    ('6:30 PM', '5:30 PM'),
    ('6:00 PM', '6:00 PM'),
    ('6:30 PM', '6:30 PM'),
    ('7:00 PM', '7:00 PM'),
    ('7:30 PM', '7:30 PM'),
    ('8:00 PM', '8:00 PM'),
    ('8:30 PM', '8:30 PM'),
    ('8:30 PM', '8:30 PM'),
    ('9:00 PM', '9:00 PM'),
    ('9:30 PM', '9:30 PM'),
    ('10:00 PM', '10:00 PM'),
    ('10:30 PM', '10:30 PM'),
    ('11:00 PM', '11:00 PM'),
    ('11:30 PM', '11:30 PM'),

)


def isAdd(n):
    Pattern = re.compile("^[a-zA-Z0-9.,""'' ]+$")
    return Pattern.match(n)


def isPhone(n):
    Pattern = re.compile("^((\+44\s?\d{4}|\(?\d{5}\)?)\s?\d{6})|((\+44\s?|0)7\d{3}\s?\d{6})$")
    return Pattern.match(n)
def isUkPhone(n):
    Pattern = re.compile("^(?:0|\+?44)\s?(?:\d\s?){9,11}$")
    return Pattern.match(n)


class bookForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name", max_length=30)
    time = forms.CharField(widget=forms.Select(choices=CHOICES))
    phone = forms.CharField()
    email = forms.EmailField(label="Email Address")
    number_of_people = forms.IntegerField(label="No of People", widget=forms.NumberInput())
    message = forms.CharField(label="Message", widget=forms.Textarea(attrs={
        'rows': 3,
        'cols': 40,
        'padding': '10px',
        'placeholder': "Enter  your Text here",
    }))

    class Meta:
        model = book
        fields = ['first_name', 'last_name', 'date', 'time', 'phone', 'email', 'number_of_people', 'message']
        widgets = {
            'email': forms.EmailInput(),
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if len(first_name) < 4:
            raise ValidationError("** minimum 4 character allowed")

        if first_name.replace(" ", "").isalpha():
            return first_name
        else:
            raise ValidationError("** only character are allowed")

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if len(last_name) < 4:
            raise ValidationError("** minimum 4 character allowed")

        if last_name.replace(" ", "").isalpha():
            return last_name
        else:
            raise ValidationError("** only character are allowed")

    def clean_date(self):
        date = self.cleaned_data.get('date')
        today = date.today()
        if date < today:
            raise ValidationError("** date is not valid")
        else:
            return date

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        print(phone)
        if isPhone(phone):
            print("ok")
            return phone
        else:
            print("no")
            raise ValidationError("** use a valid UK format")

    def clean_number_of_people(self):
        number_of_people = self.cleaned_data.get('number_of_people')
        if number_of_people > 0 and number_of_people < 100:
            return number_of_people
        else:
            raise ValidationError("** Enter a valid number")

    def clean_message(self):
        message = self.cleaned_data.get('message')
        if isAdd(message):
            return message
        else:
            raise ValidationError("** enter a valid text")


class ContactForm(forms.ModelForm):
    name=forms.CharField(label="Name",max_length=30)
    email=forms.EmailField(max_length=200,label="Email Address")
    phone=forms.CharField(widget=forms.TextInput(attrs={
        'onkeypress' : "return event.charCode >= 8 && event.charCode <= 57",
    }))
    message = forms.CharField(label="Message", widget=forms.Textarea(attrs={
        'rows': 3,
        'cols': 40,
        'padding': '10px',
        'placeholder': "Enter  your Text here",
    }))

    class Meta:
        model=contact
        fields='__all__'

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) < 4:
            raise ValidationError("** minimum 4 character allowed")

        if name.replace(" ", "").isalpha():
            return name
        else:
            raise ValidationError("** only character are allowed")

    def clean_message(self):
        message = self.cleaned_data.get('message')
        if isAdd(message):
            return message
        else:
            raise ValidationError("** enter a valid text")

    def clean_phone(self):
        phone = str(self.cleaned_data.get('phone'))
        if isUkPhone(phone):
            return phone
        else:
            raise ValidationError("** use a valid UK format")

App_Lakshabay/views.py
from django.contrib import messages
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.template.loader import render_to_string

from App_Lakshabay.forms import bookForm, ContactForm
from App_Lakshabay.models import *
from App_Order.models import *

def get_temp_user(request):
    users = TempCart.objects.all()
    if len(users) > 0:
        get_id = users.last()
        get_id = get_id.id
        print("last user id =", get_id)
    else:
        get_id = 0
        print("new", get_id)
    if "user_id" not in request.session:
        request.session["user_id"] = int(get_id) + 1

def getcart(request):
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, purchased=False)
    else:
        carts = TempCart.objects.filter(user_id=request.session['user_id'], purchased=False)
    return carts
def getorder(request):
    if request.user.is_authenticated:
        orders = Order.objects.filter(user=request.user, ordered=False)
        if len(orders) != 0:
            order = orders[0]
        else:
            order = []
    else:
        orders = TempOrder.objects.filter(user_id=request.session['user_id'], ordered=False)
        if len(orders) != 0:
            order = orders[0]
        else:
            order = []
    return order

def index(request):
    get_temp_user(request)
    menu_cat = menu_category.objects.all()
    itm = Fitem.objects.all()
    gallery_photo=gallery.objects.all().order_by("-gallery_id")
    context = {
        'carts': getcart(request),
        'order': getorder(request),
        'menu_cat': menu_cat,
        'itm': itm,
        'gallery':gallery_photo,
    }
    return render(request,'App_Lakshabay/index.html',context)


def MenuView(request):
    menu_cat = menu_category.objects.all()
    itm = Fitem.objects.all()

    context = {
        'carts': getcart(request),
        'order': getorder(request),
        'menu_cat': menu_cat,
        'itm': itm,
    }
    return render(request,'App_Lakshabay/menu.html',context)

def onlineorder(request):
    menu_cat = menu_category.objects.all()
    itm = Fitem.objects.all()
    context = {
        'carts': getcart(request),
        'order': getorder(request),
        'menu_cat': menu_cat,
        'itm': itm,
    }
    return render(request,'App_Lakshabay/onlineorder.html',context)



def GiftView(request):
    cats=category.objects.all()
    gif=gift.objects.all()
    context = {
        'carts': getcart(request),
        'order': getorder(request),
        'gifts': gif,
        'cats': cats,
    }
    return render(request, 'App_Lakshabay/gift.html', context)

def Bookview(request):
    new_form = bookForm()
    if request.method == 'POST':
        new_form = bookForm(request.POST)
        if new_form.is_valid():
            new_form.save()
            messages.success(request, 'Your booking is listed', extra_tags="book")
            return redirect('App_Lakshabay:book')


    context = {
        'carts': getcart(request),
        'order': getorder(request),
        'bookForm': new_form,
    }
    return render(request, 'App_Lakshabay/booktable.html', context)

def ContactusView(request):
    if request.method=="POST":
        form=ContactForm(request.POST)
        if form.is_valid():
            form.save()
            message = render_to_string('App_Lakshabay/message.html', {
                'email': form.cleaned_data.get('email'),
                'name': form.cleaned_data.get('name'),
                'pho': form.cleaned_data.get('phone'),
                'subject': "contact us",
                'message': form.cleaned_data.get('message'),
            })
            email = EmailMessage(
                "Message received confirmation", message, to=[settings.EMAIL_HOST_USER, ]
            )
            email.send()
            messages.success(request, 'We received your request, We will contact you soon.', extra_tags="book")
            return redirect('App_Lakshabay:contactus')
    else:
        form=ContactForm()
    context={
        'form':form,
        'carts': getcart(request),
        'order': getorder(request),
    }
    return render(request, 'App_Lakshabay/contact.html',context)


def GalleryView(request):
    images=gallery.objects.all()
    context = {
        'carts': getcart(request),
        'order': getorder(request),
        'gallery': images,
    }
    return render(request, 'App_Lakshabay/gallery.html', context)

templates/App_Lakshabay/booktable.html
{% extends 'App_Lakshabay/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
            <section  id="menu" class="menu-area ptb-100">
                <div class="container">
                    <div class="section-title">
                        <h2>Make a Reservation</h2>
                    </div>
                     {%for message in messages %}
                    {%if "book" in message.tags %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong> {{ message }}</strong>
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                 {% endfor %}
                    <div  class="col-lg-12 col-md-12">
                                <form  id="contactForm" method="post">{% csrf_token %}
                                    <div  class="row">
                                        <div  class="form-group col-lg-6 col-md-6 mb-3">
                                                 {{ bookForm.first_name|as_crispy_field }}
                                        </div >
                                        <div  class="form-group col-lg-6 col-md-6 mb-3">
                                                 {{ bookForm.last_name|as_crispy_field }}
                                        </div >
                                    </div>
                                    <div class="row">
                                        <div  class="form-group col-lg-6 col-md-6 mb-3">
                                            {{ bookForm.email|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-lg-6 col-md-6 mb-3">
                                            {{ bookForm.phone|as_crispy_field }}
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="form-group col-lg-4  col-md-4 mb-3">
                                            {{ bookForm.date|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-lg-4  col-md-4 mb-3">
                                            {{ bookForm.time|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-lg-4 col-md-4 mb-3">
                                            {{ bookForm.number_of_people|as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="form-group col-lg-12  col-md-12 mb-3">
                                        {{ bookForm.message|as_crispy_field }}
                                    </div>

                                    <div class="col-lg-12 col-md-12">
                                        <button  type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form >
                            </div>

                </div>
                <div class="line-bg">
                    <img  src="{% static  'assets/img/line.png' %}" alt="line" />
                </div>
            </section>


{% endblock %}

templates/App_Lakshabay/contact.html
{% extends 'App_Lakshabay/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
            <section  id="menu" class="menu-area ptb-100">
                <div class="container">
                    <div class="section-title">
                        <h2>Contact Us</h2>
                    </div>
                     {%for message in messages %}
                    {%if "book" in message.tags %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong> {{ message }}</strong>
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                 {% endfor %}
                    <div  class="col-lg-12 col-md-12">
                        <form  id="contactForm" method="post">{% csrf_token %}
                            <div class="row">
                                <div class="form-group col-lg-4  col-md-4 mb-3">
                                    {{ form.name|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-4  col-md-4 mb-3">
                                    {{ form.email|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-4 col-md-4 mb-3">
                                    {{ form.phone|as_crispy_field }}
                                </div>
                            </div>
                            <div class="form-group col-lg-12  col-md-12 mb-3">
                                {{ form.message|as_crispy_field }}
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <button  type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form >
                    </div>

                </div>
                <div class="line-bg">
                    <img  src="{% static  'assets/img/line.png' %}" alt="line" />
                </div>
            </section>


{% endblock %}

templates/App_Lakshabay/gallery.html
{% extends 'App_Lakshabay/base.html' %}
{% load static %}
{% block content %}

                <section  id="gallery" class="gallery-area ptb-100 pb-0">
                    <div  class="container">
                        <div class="section-title">
                            <span>Gallery</span>
                            <h2>LAKSHA BAY GALLERY</h2>
                        </div>
                    </div>
                    <div class="row m-0 p-4">
                        {% for g in gallery %}
                        <div  class="col-lg-3 col-sm-6 col-md-6 p-0">
                            <div class="single-image">
                                <img src="{{ g.image.url }}" alt="gallery-img">
                                <a  href="{{ g.image.url }}" class="popup-btn">
                                    <i class="icofont-search-restaurant"></i></a>
                                <div  class="image-content">
                                    <h3><a  href="">{{ g.gallery_name }}</a></h3>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </section>

{% endblock %}

templates/App_Lakshabay/gift.html
{% extends 'App_Lakshabay/base.html' %}
{% load static %}
{% block content %}
    <style>
        .cart-btn{
                background: #ffffff;
    padding: 2px 6px;
    border-radius: 5px;
    text-decoration: none;
    color: #000000;
        }
    </style>
            <section  class="menu-area ptb-100">
                <div class="container">
                    <div class="section-title">
                        <span>Discover</span>
                        <h2>Our Special Gift's Zone</h2>
                    </div>
                    <div class="tab">
                        <ul class="tabs active">

                              {%for cat in cats%}
                                <li>
                                <a class="tablinks" onclick="openCity(event, '{{ cat.category_id }}')">
                                    <i class="icofont-gift">

                                    </i>
                                    <h6>{{ cat }}</h6>
                                </a>
                            </li>
                        {% endfor %}
                        </ul>
                        <div class="tab_content" >
                             {%for cat in cats %}
                                <div id="{{ cat.category_id }}" class="tabs_item">
                                    <div class="row">
                                       {% for foo in  gifts %}
                                            {% if foo.gift_category == cat %}
                                       <div class="col-lg-6 col-md-12">
                                            <div  class="single-menu" >
                                                <div  class="food-menu-content">
                                                    <h3>{{ foo.gift_name }} <span  class="menu-price">&#163;{{ foo.gift_price }}</span></h3>
                                                    <p class="text-light">{{ foo.gift_description }}</p>
                                                </div>
                                                <a class="cart-btn" href="{% url 'App_Order:add' pk=foo.pk  %}">Add to Cart</a>
                                            </div>
                                        </div>
                                           {% endif %}
                                       {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
                <div  class="line-bg"><img src="{% static  'assets/img/line.png' %}" alt="line" /></div>
            </section>


{% endblock %}

templates/App_Lakshabay/menu.html
{% extends 'App_Lakshabay/base.html' %}
{% load static %}
{% block content %}
            <section  class="menu-area ptb-100">
                <div class="container">
                    <div class="section-title">
                        <span>Discover</span>
                        <h2>Our Special Menu</h2>
                    </div>
                   <div class="tab">
                    <ul class="tabs active">
                               {%for cat in menu_cat%}
                                <li>
                                <a class="tablinks" onclick="openCity(event, '{{ cat.menu_cat_id }}')">
                                    <i>
                                        <img src="{{ cat.file.url }}" width="30" height="30">
                                    </i>
                                    <h6>{{ cat }}</h6>
                                </a>
                            </li>
                        {% endfor %}
                        </ul>
                        <div class="tab_content">
                             {%for cat in menu_cat %}
                                <div id="{{ cat.menu_cat_id }}" class="tabs_item">
                                    <div class="row">
                                       {% for foo in  itm %}
                                            {% if foo.item_category == cat %}
                                                <div class="col-lg-6 col-md-12">
                                            <div  class="single-menu" >
                                                <div  class="food-menu-content">
                                                    <p class="text-light">{{ foo.item_description }}</p>
                                                </div>
                                                <a class="cart-btn" href="{% url 'App_Order:item_ad' foo.item_id %}">Add to Cart</a>
                                            </div>
                                        </div>
                                            {% endif %}
                                       {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
                <div class="line-bg">
                    <img  src="{% static 'assets/img/line.png' %}" alt="line" /></div>
            </section>


{% endblock %}

templates/App_Lakshabay/onlineorder.html
{% extends 'App_Lakshabay/base.html' %}
{% load static %}
{% block content %}
<style>
.tabs_item {
  display: none;
  padding: 6px 12px;
  -webkit-animation: fadeEffect 1s;
  animation: fadeEffect 1s;
  animation: 0s linear 2.3s forwards delayedShow ;
}
</style>
            <section  id="menu" class="menu-area ptb-100">
                <div class="container">
                    <div class="section-title">
                        <span>Discover</span>
                        <h2>Our Special Food Item's</h2>
                    </div>
                    <div class="tab">
                    <ul class="tabs active">
                               {%for cat in menu_cat%}
                                <li>
                                <a class="tablinks" onclick="openCity(event, '{{ cat.menu_cat_id }}')">
                                    <i>
                                        <img src="{{ cat.file.url }}" width="30" height="30">
                                    </i>
                                    <h6>{{ cat }}</h6>
                                </a>
                            </li>
                        {% endfor %}
                        </ul>
                        <div class="tab_content">
                             {%for cat in menu_cat %}
                                <div id="{{ cat.menu_cat_id }}" class="tabs_item">
                                    <div class="row">
                                       {% for foo in  itm %}
                                            {% if foo.item_category == cat %}
                                                <div class="col-lg-6 col-md-12">
                                            <div  class="single-menu" >
                                                <div  class="food-menu-content">
                                                    <h3>{{ foo.item_name }} <span  class="menu-price">&#163;{{ foo.item_price }}</span></h3>
                                                    <p class="text-light">{{ foo.item_description }}</p>
                                                </div>
                                                <a class="cart-btn" href="{% url 'App_Order:item_ad' foo.item_id %}">Add to Cart</a>
                                            </div>
                                        </div>
                                            {% endif %}
                                       {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
                <div class="line-bg">
                    <img  src="{% static 'assets/img/line.png' %}" alt="line" /></div>
            </section>

<script>
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabs_item");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>

{% endblock %}