App_Lakshabay/urls.py
from django.urls import path
from App_Lakshabay import views
app_name='App_Lakshabay'
urlpatterns = [
    path('',views.index,name='index'),
    path('menu/', views.MenuView, name='menus'),
    path('onlineorder/', views.onlineorder, name='onlineorder'),
    path('gifts/', views.GiftView, name='gifts'),
    path('book/', views.Bookview, name='book'),
    path('contact-us',views.ContactusView,name='contactus'),
    path('gallery/', views.GalleryView, name='gallery_image'),
]

App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name="cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),

    path('add-food/<pk>/', views.item_add_to_cart, name="item_ad"),
    path('item-cart/', views.item_cart_view, name="item_cart"),
    path('item-increase/<pk>/', views.itemincrease_cart, name="item_increase"),
    path('item-decrease/<pk>/', views.itemdecrease_cart, name="item_decrease"),
    path('item-remove/<pk>/', views.itemremove_from_cart, name="item_remove"),


]

App_Superadmin/urls.py
from django.urls import path
from App_Superadmin import views
app_name="App_Superadmin"
urlpatterns = [
    path('', views.Dashboard, name='dashboard'),
    path('superadmin-login', views.SuperadminLogin, name="superadmin_login"),
    path('superadmin-logout', views.SuperadminLogout, name="superadmin_logout"),


    path('oderlist/',views.Oderlist,name='oderlist'),
    path('view-order-details/<int:id>',views.ViewOrderDetails,name="orderdetails"),
    path('delete-order/<int:id>',views.DeletereOrder,name='delete_order'),

    path('category/', views.CategoryView, name="category"),
    path('delete/<int:id>', views.CatDeleteView, name="category_delete"),
    path('update/<int:id>', views.CatUpdateView, name="category_update"),

    path('menu-category/', views.MunuCategoryView, name="menu-category"),
    path('menu-delete/<int:id>', views.MenuCatDeleteView, name="menu_category_delete"),
    path('menu-update/<int:id>', views.MenuCatUpdateView, name="menu_category_update"),

    path('food-item/', views.FoodItem, name="food_item"),
    path('food-delete/<int:id>', views.FoodItemDeleteView, name="food_item_delete"),
    path('food-update/<int:id>', views.FoodItemUpdateView, name="food_item_update"),

    path('food-gifts/', views.GiftView, name="gift"),
    path('food-gift-update/<int:id>', views.GiftUpdate, name="gift_update"),
    path('food-gift-delete/<int:id>', views.GiftDelete, name="gift_delete"),

    path('gallary-view/', views.Gallaryview, name="gallary"),
    path('gallary-update/<int:id>', views.GallaryUpdate, name="gallary_update"),
    path('gallary-delete/<int:id>', views.GallarytDelete, name="gallary_delete"),

    path('booking/', views.Bookingview, name="booking"),
    path('booking-delete/<int:id>', views.BookingDelete, name="booking_delete"),
    path('booking-update/<int:id>', views.BookingUpdate, name="booking_update"),

    path('profile-view', views.ProfileView, name="profile"),
    path('profile-delete/<int:id>', views.ProfileDelete, name="profile_delete"),

    path('billing', views.BillingView, name="billing"),
    path('update-billing/<int:id>', views.UpdateBillingView, name="updatebilling"),
    path('delete-billing/<int:id>', views.DeleteBillingView, name="deletebilling"),

]

lakshabay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Lakshabay.urls')),
    path('', include('App_Order.urls')),
    path('', include('App_Payment.urls')),
    path('superadmin/',include('App_Superadmin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

App_Superadmin/models.py
from django.db import models

# Create your models here.

App_Superadmin/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render,HttpResponse,redirect
from App_Lakshabay.forms import *
from App_Payment.forms import *
from App_Payment.models import *
from App_Order.models import *

def Dashboard(request):
    if request.user.is_superuser and request.user.is_authenticated:
        alluser=User.objects.all().exclude(is_superuser=True)
        orders=Order.objects.filter(ordered=True)
        items=Fitem.objects.all()
        booking=book.objects.all()
        context={
            'users':alluser,
            'orders':orders,
            'food_category':items,
            'bookings':booking,
        }
        return render(request,'App_Superadmin/index.html',context)
    else:
        return redirect('App_Superadmin:superadmin_login')
def Deleteuser(request,id):
    if request.user.is_superuser:
        if User.objects.filter(id=id).exists():
            us=User.objects.get(id=id)
            us.delete()
            messages.success(request,"User removed successfully",extra_tags="dashboard")
            return redirect('App_Superadmin:dashboard')
    else:
        return HttpResponse("<h1>You are not allow to delete any user</h1>")		
def SuperadminLogin(request):
    if request.user.is_authenticated and request.user.is_superuser:
        return redirect('App_Superadmin:dashboard')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            print(username,password)
            user = authenticate(request, username=username, password=password)
            print(user)
            if user is not None:
                login(request, user)
                if request.user.is_superuser:
                    return redirect('App_Superadmin:dashboard')
                else:
                    messages.info(request, "You are not a superuser",extra_tags="login")
                    return redirect('App_Superadmin:superadmin_login')
            else:
                messages.info(request, "Enter correct username and password",extra_tags="login")
                return redirect('App_Superadmin:superadmin_login')

        else:
            return render(request, 'App_Superadmin/login.html')



def SuperadminLogout(request):
    logout(request)
    return redirect('App_Superadmin:superadmin_login')

def Oderlist(request):
    orders = Order.objects.filter(ordered=True).order_by("-id")
    context = {
        'orders': orders,
    }
    return render(request, 'App_Superadmin/oderlist.html', context)


def ViewOrderDetails(request,id):
    if Order.objects.filter(id=id).exists():
        ord=Order.objects.get(id=id)
        context={
            'ord':ord,
        }
        return render(request,'App_Superadmin/order_details.html',context)
    else:
        return HttpResponse("<h1>Order is invalid</h1>")


def DeletereOrder(request, id):
    if request.user.is_superuser:
        if Order.objects.filter(id=id).exists():
            ord = Order.objects.get(id=id)
            ord.delete()
            messages.success(request, "Order removed successfully", extra_tags="deleteorder")
            return redirect('App_Superadmin:oderlist')
    else:
        return HttpResponse("<h1>You are not allow to delete any order</h1>")


def CategoryView(request):
    cat = category.objects.all()
    if request.method == "POST":
        cat = request.POST.get('cat_name')
        data = category.objects.create(
            category_name=cat
        )
        data.save()
        messages.success(request, 'Category succesfully added', extra_tags="cat_add")
        return redirect(request.POST['next'])
    context = {
        'catego': cat,
    }

    return render(request, 'App_Superadmin/categoryview.html', context)


def CatDeleteView(request, id):
    if category.objects.filter(category_id=id).exists():
        c = category.objects.get(category_id=id)
        if request.user.is_superuser:
            c.delete()
            messages.success(request, "Category succesfully deleted", extra_tags="cat_add")
            return redirect('App_Superadmin:category')
        else:
            return HttpResponse("<h1>You are not allow to delete it</h1>")
    else:
        return HttpResponse("<h1>Category not found</h1>")


def CatUpdateView(request, id):
    cat = category.objects.all()
    select_cat = category.objects.get(category_id=id)
    if request.method == "POST":
        cat_n = request.POST.get('cat_name')
        select_cat.category_name = cat_n
        select_cat.save()
        messages.success(request, 'Category succesfully updated', extra_tags="cat_add")
        return redirect('App_Superadmin:category')
    context = {
        'catego': cat,
        'select_cat': select_cat,
    }

    return render(request, 'App_Superadmin/updatecategoryview.html', context)

def MunuCategoryView(request):
    cat = menu_category.objects.all()
    if request.method == "POST":
        cat = request.POST.get('cat_name')
        data = menu_category.objects.create(
            menu_cat_name=cat
        )
        data.save()
        messages.success(request, 'Menu category succesfully added', extra_tags="menu_add")
        return redirect(request.POST['next'])
    context = {
        'catego': cat,
    }

    return render(request, 'App_Superadmin/menucategories.html', context)
def MenuCatUpdateView(request,id):
    cat = menu_category.objects.all()
    select_cat = menu_category.objects.get(menu_cat_id=id)
    if request.method == "POST":
        cat_n = request.POST.get('cat_name')
        select_cat.menu_cat_name = cat_n
        select_cat.save()
        messages.success(request, 'Menu category succesfully updated', extra_tags="menu_add")
        return redirect('App_Superadmin:menu-category')
    context = {
        'catego': cat,
        'select_cat': select_cat,
    }

    return render(request, 'App_Superadmin/updatemenucategoryview.html', context)
def MenuCatDeleteView(request,id):
    if menu_category.objects.filter(menu_cat_id=id).exists():
        c = menu_category.objects.get(menu_cat_id=id)
        if request.user.is_superuser:
            c.delete()
            messages.success(request, "Menu Category succesfully deleted", extra_tags="menu_add")
            return redirect('App_Superadmin:menu-category')
        else:
            return HttpResponse("<h1>You are not allow to delete it</h1>")
    else:
        return HttpResponse("<h1>Menu category not founded</h1>")


def FoodItem(request):
    fooditems=Fitem.objects.all().order_by("-item_id")
    menu_cat=menu_category.objects.all()
    if request.method=="POST":
        name=request.POST['item_name']
        des=request.POST['description']
        price=request.POST['item_price']

        cat=request.POST['category']
        print("cat id =",cat)
        if len(request.FILES) > 0:
            pho = request.FILES['item_photo']
            cate_name=menu_category.objects.get(menu_cat_id=cat)
            item=Fitem.objects.create(
                item_name=name,item_category=cate_name,item_description=des,item_price=price,photo=pho
            )
            item.save()
            messages.success(request,"Food Item Save succesfully",extra_tags="food_item")
            return redirect(request.POST['next'])
        else:
            cate_name = menu_category.objects.get(menu_cat_id=cat)
            item = Fitem.objects.create(
                item_name=name, item_category=cate_name, item_description=des, item_price=price
            )
            item.save()
            messages.success(request, "Food Item Save succesfully", extra_tags="food_item")
            return redirect(request.POST['next'])
    context={
        'food_items':fooditems,
        'menu_cat':menu_cat,

    }
    return render(request,'App_Superadmin/fooditems.html',context)

def FoodItemDeleteView(request,id):
    if Fitem.objects.filter(item_id=id).exists():
        c = Fitem.objects.get(item_id=id)
        if request.user.is_superuser:
            c.delete()
            messages.success(request, "Food Item succesfully deleted", extra_tags="food_item")
            return redirect('App_Superadmin:food_item')
        else:
            return HttpResponse("<h1>You are not allow to delete it</h1>")
    else:
        return HttpResponse("<h1>Menu category not founded</h1>")
def FoodItemUpdateView(request,id):
    fooditems = Fitem.objects.all().order_by("-item_id")
    menu_cat = menu_category.objects.all()
    my_item=Fitem.objects.get(item_id=id)
    if request.method == "POST":
        name = request.POST['item_name']
        des = request.POST['description']
        price = request.POST['item_price']

        cat = request.POST['category']
        pho=my_item.photo
        if len(request.FILES) > 0:
            pho = request.FILES['item_photo']
        cate_name = menu_category.objects.get(menu_cat_id=cat)
        my_item.item_name=name
        my_item.item_category=cate_name
        my_item.item_description=des
        my_item.item_price=price
        my_item.photo=pho
        my_item.save()
        messages.success(request, "Food Item update succesfully", extra_tags="food_item")
        return redirect('App_Superadmin:food_item')
    context = {
        'food_items': fooditems,
        'menu_cat': menu_cat,
        'my_item':my_item,

    }
    return render(request, 'App_Superadmin/fooditemupdate.html', context)


def GiftView(request):
    allgifts=gift.objects.all().order_by("-gift_id")
    cats=category.objects.all()
    if request.method=="POST":
        g_name=request.POST.get('gift_name')
        g_serial=request.POST.get('gift_serial')
        g_category=request.POST.get('gift_category')
        g_type=request.POST.get('gift_type')
        g_meta=request.POST.get('gift_meta')
        g_price=request.POST.get('gift_price')
        g_des=request.POST.get('gift_description')

templates/App_Superadmin/billingaddress.html
{% extends 'App_Superadmin/base.html' %}
{% load static %}
{% block content %}
 <div class="container-fluid" id="container-wrapper">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Billing Management</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'App_Lakshabay:index' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
            </ol>
          </div>
            <div class="col-lg-12 m-0 m-auto">
                 {%for message in messages %}
                    {%if "bill" in message.tags %}
                    <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                    {{ message }}
                  </div>
                    {% endif %}
                 {% endfor %}
              <!-- General Element -->
            </div>
          <div class="row mb-3">
          <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Billing Datatable</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                    <thead class="thead-light">
                      <tr>
                        <th>No</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Company</th>
                        <th>City</th>
                        <th>Phone</th>
                        <th>Action</th>
                      </tr>

                    </thead>
                    <tbody>
                    {% for g in billings %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ g.firstname }}</td>
                        <td>{{ g.lastname }}</td>
                        <td>{{ g.company }}</td>
                        <td>{{ g.city }}</td>
                        <td>{{g.phone }}</td>
                        <td>
                            <a href="{% url 'App_Superadmin:deletebilling' g.id %}"  onclick="return confirm('Are you sure you want to delete this item?');">
                                <i class="fas fa-fw fa-trash" style="color: #801d3b;"></i>
                            </a>
                            <a href="{% url 'App_Superadmin:updatebilling' g.id %}"><i class="fas fa-fw fa-edit" style="color: #801d3b;"></i></a>
                        </td>
                      </tr>
                     {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <!--Row-->

          <!-- Modal Logout -->
          <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelLogout"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Are you sure you want to logout?</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                  <a href="{% url 'App_Superadmin:superadmin_logout' %}" class="btn btn-primary">Logout</a>
                </div>
              </div>
            </div>
          </div>

        </div>
{% endblock %}

templates/App_Superadmin/gallaryviewpage.html
{% extends 'App_Superadmin/base.html' %}
{% load static %}
{% block content %}
 <div class="container-fluid" id="container-wrapper">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Gallery Management</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'App_Lakshabay:index' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
            </ol>
          </div>
            <div class="col-lg-7 m-0 m-auto">
                 {%for message in messages %}
                    {%if "gallary" in message.tags %}
                    <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                    {{ message }}
                  </div>
                    {% endif %}
                 {% endfor %}
              <!-- General Element -->
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Add Photo to Gallery</h6>
                </div>
                <div class="card-body">
                  <form method="post" action="{% url 'App_Superadmin:gallary' %}" enctype="multipart/form-data">{% csrf_token %}
                      <div class="form-group">
                          <label for="exampleInputEmail1">Gallery Name</label>
                          <input type="text" class="form-control" name="gallary_name" placeholder="Enter gallary name" required>
                    </div>
                    <div class="form-group">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input" id="customFile" name="gallary_photo" required>
                        <label class="custom-file-label" for="customFile">Choose photo</label>
                      </div>
                    </div>

                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>

            </div>
          <div class="row mb-3">
          <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Gallery Datatable</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                    <thead class="thead-light">
                      <tr>
                        <th>No</th>
                        <th>Gallery Name</th>
                        <th>Photo</th>
                        <th>Action</th>
                      </tr>

                    </thead>
                    <tbody>
                    {% for g in gallary %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ g.gallery_name }}</td>
                        <td>
                            <img src="{{ g.image.url }}" width="60px" height="60px">
                        </td>
                        <td>
                            <a href="{% url 'App_Superadmin:gallary_delete' g.gallery_id %}"  onclick="return confirm('Are you sure you want to delete this item?');">
                                <i class="fas fa-fw fa-trash" style="color: #801d3b;"></i>
                            </a>
                            <a href="{% url 'App_Superadmin:gallary_update' g.gallery_id %}"><i class="fas fa-fw fa-edit" style="color: #801d3b;"></i></a>
                        </td>
                      </tr>
                     {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <!--Row-->

          <!-- Modal Logout -->
          <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelLogout"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Are you sure you want to logout?</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                  <a href="{% url 'App_Superadmin:superadmin_logout' %}" class="btn btn-primary">Logout</a>
                </div>
              </div>
            </div>
          </div>

        </div>
{% endblock %}

templates/App_Superadmin/giftspage.html
{% extends 'App_Superadmin/base.html' %}
{% load static %}
{% block content %}
 <div class="container-fluid" id="container-wrapper">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Gift Management</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'App_Lakshabay:index' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
            </ol>
          </div>
            <div class="col-lg-10 m-0 m-auto">
                 {%for message in messages %}
                    {%if "gift" in message.tags %}
                    <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                    {{ message }}
                  </div>
                    {% endif %}
                 {% endfor %}
              <!-- General Element -->
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Add Gift</h6>
                </div>
                <div class="card-body">
                  <form method="post" action="{% url 'App_Superadmin:gift' %}" enctype="multipart/form-data">{% csrf_token %}
                      <div class="form-row">
                      <div class="form-group col-md-6">
                          <label for="exampleInputEmail1">Gift Name</label>
                          <input type="text" class="form-control" name="gift_name" placeholder="Enter gift name" required>
                    </div>
                     <div class="form-group col-md-6">
                          <label for="exampleInputEmail1">Gift Serial</label>
                          <input type="text" class="form-control" name="gift_serial" placeholder="Enter gift serial" required>
                    </div>
                      </div>
                       <div class="form-row">
                      <div class="form-group col-md-6">
                          <label for="exampleInputEmail1">Gift Category</label>
                          <select class="form-control" id="exampleFormControlSelect1" name="gift_category">
                           {% for c in cats %}
                            <option value="{{ c.category_id }}">{{ c.category_name }}</option>
                            {% endfor %}
                          </select>
                    </div>
                     <div class="form-group col-md-6">
                          <label for="exampleInputEmail1">Gift Type</label>
                          <select class="form-control" id="exampleFormControlSelect1" name="gift_type">
                            <option value="Voucher">Voucher</option>
                            <option value="Product">Product</option>
                          </select>
                    </div>
                      </div>
                  <div class="form-row">
                      <div class="form-group col-md-9">
                          <label for="exampleInputEmail1">Gift Meta</label>
                          <input type="text" class="form-control" name="gift_meta" placeholder="Enter gift meta" required>
                    </div>
                     <div class="form-group col-md-3">
                          <label for="exampleInputEmail1">Gift Price</label>
                          <input type="number" step="1" onkeypress="return event.charCode >= 8 && event.charCode <= 57" class="form-control" name="gift_price" placeholder="Enter gift price" required>
                    </div>
                      </div>
                  <div class="form-group">
                      <label for="exampleFormControlTextarea1">Description</label>
                      <textarea class="form-control" id="exampleFormControlTextarea1" name="gift_description" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input" id="customFile" name="gift_images" required>
                        <label class="custom-file-label" for="customFile">Choose photo</label>
                      </div>
                    </div>

                      <input type="hidden" name="next" value="{{ request.path }}">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>

            </div>
          <div class="row mb-3">
          <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Gift's Datatable</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                    <thead class="thead-light">
                      <tr>
                        <th>No</th>
                        <th>Gift Name</th>
                        <th>Gift Serial</th>
                        <th>Gift Category</th>
                        <th>Gift Type</th>
                        <th>Gift Price</th>
                        <th>Action</th>
                      </tr>

                    </thead>
                    <tbody>
                    {% for g in allgift %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ g.gift_name }}</td>
                        <td>{{ g.gift_sl_no }}</td>
                        <td>{{ g.gift_category.category_name }}</td>
                        <td>{{ g.gift_type }}</td>
                        <td>{{ g.gift_price }}</td>
                        <td>
                            <a href="{% url 'App_Superadmin:gift_delete' g.gift_id %}"  onclick="return confirm('Are you sure you want to delete this item?');">
                                <i class="fas fa-fw fa-trash" style="color: #801d3b;"></i>
                            </a>
                            <a href="{% url 'App_Superadmin:gift_update' g.gift_id %}"><i class="fas fa-fw fa-edit" style="color: #801d3b;"></i></a>
                        </td>
                      </tr>
                     {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <!--Row-->

          <!-- Modal Logout -->
          <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelLogout"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Are you sure you want to logout?</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                  <a href="{% url 'App_Superadmin:superadmin_logout' %}" class="btn btn-primary">Logout</a>
                </div>
              </div>
            </div>
          </div>

        </div>
{% endblock %}