App_Lakshabay/urls.py
from django.urls import path
from App_Lakshabay import views
app_name='App_Lakshabay'
urlpatterns = [
    path('',views.index,name='index'),
    path('menu/', views.MenuView, name='menus'),
    path('onlineorder/', views.onlineorder, name='onlineorder'),
    path('gifts/', views.GiftView, name='gifts'),
    path('book/', views.Bookview, name='book'),
    path('contact-us',views.ContactusView,name='contactus'),
    path('gallery/', views.GalleryView, name='gallery_image'),
]

App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name="cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),

    path('add-food/<pk>/', views.item_add_to_cart, name="item_ad"),
    path('item-cart/', views.item_cart_view, name="item_cart"),
    path('item-increase/<pk>/', views.itemincrease_cart, name="item_increase"),
    path('item-decrease/<pk>/', views.itemdecrease_cart, name="item_decrease"),
    path('item-remove/<pk>/', views.itemremove_from_cart, name="item_remove"),


]

App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = "App_Payment"
from App_Payment.views import (
    CreateCheckoutSessionView
)
urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('payment/<int:id>',views.PaymentView,name='payment'),
    path('cancel/', views.CancelView, name='cancel'),
    path('success/', views.SuccessView, name='success'),
    path('create-checkout-session/<pk>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),

]

lakshabay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Lakshabay.urls')),
    path('', include('App_Order.urls')),
    path('', include('App_Payment.urls')),
    path('superadmin/',include('App_Superadmin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

App_Order/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.urls import reverse

from App_Payment.models import *
from App_Lakshabay.models import *


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart")
    item = models.ForeignKey(gift, on_delete=models.CASCADE, blank=True, null=True)
    item2 = models.ForeignKey(Fitem, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.item != None:
            return f'{self.quantity} X {self.item}'
        else:
            return f'{self.quantity} X {self.item2}'

    def get_total(self):
        if self.item != None:
            total = self.item.gift_price * self.quantity
            float_total = format(total, '0.2f')
            return float_total
        else:
            total = self.item2.item_price * self.quantity
            float_total = format(total, '0.2f')
            return float_total


class TempCart(models.Model):
    user_id = models.BigIntegerField()
    item = models.ForeignKey(gift, on_delete=models.CASCADE, blank=True, null=True)
    item2 = models.ForeignKey(Fitem, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.item != None:
            return f'{self.quantity} X {self.item}'
        else:
            return f'{self.quantity} X {self.item2}'

    def get_total(self):
        if self.item != None:
            total = self.item.gift_price * self.quantity
            float_total = format(total, '0.2f')
            return float_total
        else:
            total = self.item2.item_price * self.quantity
            float_total = format(total, '0.2f')
            return float_total


class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True, null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    billing_address = models.ForeignKey(BillingAddress, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return '{}'.format(str(self.user))

    def get_cart_count(self):
        return self.orderitems.count()

    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        return total

    def get_absolute_url(self):
        return reverse("App_Payment:payment", args=[self.id])

class TempOrder(models.Model):
    orderitems = models.ManyToManyField(TempCart)
    user_id = models.BigIntegerField()
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True, null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_cart_count(self):
        return self.orderitems.count()

    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        return total


		
class OrderDetail(models.Model):
    product = models.ForeignKey(Order,on_delete=models.CASCADE)
    amount = models.IntegerField(verbose_name='Amount')
    stripe_payment_intent = models.CharField(max_length=200)
    has_paid = models.BooleanField(default=False,verbose_name='Payment Status')
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}-{}'.format(self.amount,self.has_paid)		

App_Order/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect,HttpResponse
from django.contrib.auth.decorators import login_required
from App_Order.models import *
from App_Lakshabay.models import *
from django.contrib import messages
from App_Lakshabay import views as v

def item_add_to_cart(request,pk):
    if request.user.is_authenticated:
        item = get_object_or_404(Fitem, pk=pk)
        print("Item")
        print(item)
        order_item = Cart.objects.get_or_create(item2=item,user=request.user,purchased=False)
        print("Order Item Object:")
        print(order_item)
        print(order_item[0])
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        print("Order Qs:")
        print(order_qs)
        #print(order_qs[0])
        if order_qs.exists():
            order = order_qs[0]
            print("If Order exist")
            print(order)
            if order.orderitems.filter(item2=item).exists():
                order_item[0].quantity += 1
                order_item[0].save()
                messages.info(request, "This item quantity was updated.")
                return redirect("App_Lakshabay:onlineorder")
            else:
                order.orderitems.add(order_item[0])
                messages.info(request, "This item was added to your cart.")
                return redirect("App_Lakshabay:onlineorder")
        else:
            order = Order(user=request.user)
            order.save()
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect("App_Lakshabay:onlineorder")
    else:
        item = get_object_or_404(Fitem, pk=pk)
        print("Item")
        print(item)
        order_item = TempCart.objects.get_or_create(item2=item, user_id=request.session["user_id"], purchased=False)
        print("Order Item Object:")
        print(order_item)
        print(order_item[0])
        order_qs = TempOrder.objects.filter(user_id=request.session["user_id"], ordered=False)
        print("Order Qs:")
        print(order_qs)
        # print(order_qs[0])
        if order_qs.exists():
            order = order_qs[0]
            print("If Order exist")
            print(order)
            if order.orderitems.filter(item2=item).exists():
                order_item[0].quantity += 1
                order_item[0].save()
                messages.info(request, "This item quantity was updated.")
                return redirect("App_Lakshabay:onlineorder")
            else:
                order.orderitems.add(order_item[0])
                messages.info(request, "This item was added to your cart.")
                return redirect("App_Lakshabay:onlineorder")
        else:
            order = TempOrder(user_id=request.session["user_id"])
            order.save()
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect("App_Lakshabay:onlineorder")

def add_to_cart(request, pk):
    if request.user.is_authenticated:
        item = get_object_or_404(gift, pk=pk)
        print("Item")
        print(item)
        order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False,item2=None)
        print("Order Item Object:")
        print(order_item)
        print(order_item[0])
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        print("Order Qs:")
        print(order_qs)
        #print(order_qs[0])
        if order_qs.exists():
            order = order_qs[0]
            print("If Order exist")
            print(order)
            if order.orderitems.filter(item=item).exists():
                order_item[0].quantity += 1
                order_item[0].save()
                messages.info(request, "This item quantity was updated.")
                return redirect("App_Lakshabay:gifts")
            else:
                order.orderitems.add(order_item[0])
                messages.info(request, "This item was added to your cart.")
                return redirect("App_Lakshabay:gifts")
        else:
            order = Order(user=request.user)
            order.save()
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect("App_Lakshabay:gifts")
    else:
        item = get_object_or_404(gift, pk=pk)
        print("Item")
        print(item)
        order_item = TempCart.objects.get_or_create(item=item, user_id=request.session["user_id"], purchased=False,item2_id=None)
        print("Order Item Object:")
        print(order_item)
        print(order_item[0])
        order_qs = TempOrder.objects.filter(user_id=request.session["user_id"], ordered=False)
        print("Order Qs:")
        print(order_qs)
        # print(order_qs[0])
        if order_qs.exists():
            order = order_qs[0]
            print("If Order exist")
            print(order)
            if order.orderitems.filter(item=item).exists():
                order_item[0].quantity += 1
                order_item[0].save()
                messages.info(request, "This item quantity was updated.")
                return redirect("App_Lakshabay:gifts")
            else:
                order.orderitems.add(order_item[0])
                messages.info(request, "This item was added to your cart.")
                return redirect("App_Lakshabay:gifts")
        else:
            order = TempOrder(user_id=request.session["user_id"])
            order.save()
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect("App_Lakshabay:gifts")


def item_cart_view(request):
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, purchased=False,item=None)
        orders = Order.objects.filter(user=request.user, ordered=False)
        if carts.exists() and orders.exists():
            order = orders[0]
            return render(request, 'App_Order/item_cart.html', context={'carts':carts, 'order':order})
        else:
            messages.warning(request, "You don't have any item in your cart!")
            return redirect("App_Lakshabay:onlineorder")
    else:
        carts = TempCart.objects.filter(user_id=request.session['user_id'], purchased=False,item=None)
        orders = TempOrder.objects.filter(user_id=request.session['user_id'], ordered=False)
        if carts.exists() and orders.exists():
            order = orders[0]
            return render(request, 'App_Order/item_cart.html', context={'carts': carts, 'order': order})
        else:
            messages.warning(request, "You don't have any item in your cart!")
            return redirect("App_Lakshabay:onlineorder")

def cart_view(request):
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, purchased=False)
        orders = Order.objects.filter(user=request.user, ordered=False)
        print("shw=",carts)
        if carts.exists() and orders.exists():
            order = orders[0]
            return render(request, 'App_Order/cart.html', context={'carts':carts, 'order':order})
        else:
            messages.warning(request, "You don't have any item in your cart!")
            return redirect("App_Lakshabay:gifts")
    else:
        carts = TempCart.objects.filter(user_id=request.session['user_id'], purchased=False)
        orders = TempOrder.objects.filter(user_id=request.session['user_id'], ordered=False)

        if carts.exists() and orders.exists():
            order = orders[0]
            return render(request, 'App_Order/cart.html', context={'carts': carts, 'order': order})
        else:
            messages.warning(request, "You don't have any item in your cart!")
            return redirect("App_Lakshabay:gifts")


def remove_from_cart(request, pk):
    item = get_object_or_404(gift, pk=pk)
    if request.user.is_authenticated:
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.orderitems.filter(item=item).exists():
                order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
                order.orderitems.remove(order_item)
                order_item.delete()
                messages.warning(request, "This item was removed form your cart")
                return redirect("App_Order:cart")
            else:
                messages.info(request, "This item was not in your cart.")
                return redirect("App_Lakshabay:gifts")
        else:
            messages.info(request, "You don't have an active order")
            return redirect("App_Lakshabay:gifts")
    else:
        order_qs = TempOrder.objects.filter(user_id=request.session['user_id'], ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.orderitems.filter(item=item).exists():
                order_item = TempCart.objects.filter(item=item, user_id=request.session['user_id'], purchased=False)[0]
                order.orderitems.remove(order_item)
                order_item.delete()
                messages.warning(request, "This item was removed form your cart")
                return redirect("App_Order:cart")
            else:
                messages.info(request, "This item was not in your cart.")
                return redirect("App_Lakshabay:gifts")
        else:
            messages.info(request, "You don't have an active order")
            return redirect("App_Lakshabay:gifts")


def increase_cart(request, pk):
    item = get_object_or_404(gift, pk=pk)
    if request.user.is_authenticated:
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]

templates/App_Order/cart.html
{% extends 'App_Lakshabay/base.html' %}
{% load static %}
{% block content %}
    <style>
        .cart-btn{
                background: #ffffff;
    padding: 2px 6px;
    border-radius: 5px;
    text-decoration: none;
    color: #000000;
        }
    .shopping-cart {
  width: 750px;
  height: auto;
  margin: 80px auto;
  background: #FFFFFF;
  box-shadow: 1px 2px 3px 0px rgba(0,0,0,0.10);
  border-radius: 6px;
  display: flex;
  flex-direction: column;
}
    .title {
  height: 60px;
  border-bottom: 1px solid #E1E8EE;
  padding: 20px 30px;
  color: #5E6977;
  font-size: 18px;
  font-weight: 400;
}

.item {
  padding: 20px 30px;
  height: 120px;
  display: flex;
}

.item:nth-child(20) {
  border-top:  1px solid #E1E8EE;
  border-bottom:  1px solid #E1E8EE;
}
    .buttons {
  position: relative;
  padding-top: 30px;
  margin-right: 60px;
}
@keyframes animate {
  0%   { background-position: left;  }
  50%  { background-position: right; }
  100% { background-position: right; }
}

.description {
  padding-top: 15px;
  margin:0 auto;
  width: auto;
}

.description span {
  display: block;
  font-size: 14px;
  color: #43484D;
  font-weight: 400;
}

.description span:first-child {
  margin-bottom: 5px;
}
.description span:last-child {
  font-weight: 300;
  margin-top: 8px;
  color: #86939E;
}
    .quantity {
  padding-top: 20px;
  margin-right: 60px;
}
.quantity input {
  -webkit-appearance: none;
  border: none;
  text-align: center;
  width: 32px;
  font-size: 16px;
  color: #43484D;
  font-weight: 300;
}

button[class*=btn] {
  width: 30px;
  height: 30px;
  background-color: #E1E8EE;
  border-radius: 6px;
  border: none;
  cursor: pointer;
}
.minus-btn img {
  margin-bottom: 3px;
}
.plus-btn img {
  margin-top: 2px;
}

button:focus,
input:focus {
  outline:0;
}
.total-price {
  width: 83px;
  padding-top: 21px;
  text-align: center;
  font-size: 16px;
  color: #43484D;
  font-weight: 300;
}
@media (max-width: 800px) {
  .shopping-cart {
    width: 100%;
    height: auto;
    overflow: hidden;
  }
  .item {
    height: auto;
    flex-wrap: wrap;
    justify-content: center;
  }
  .image img {
    width: 50%;
  }
  .image,
  .quantity,
  .description {
    width: 100%;
    text-align: center;
    margin: 6px 0;
  }
  .buttons {
    margin-right: 20px;
  }
}
</style>
    <section class="menu-area ptb-100">
    <div class="container">
         <div class="section-title">
            <span>Discover</span>
               <h2>Our Cart Zone</h2>
          </div>

                          {%for message in messages %}
                     {%if "cart" in message.tags %}
                      <div class="alert alert-primary" role="alert">
                     {{ message }}
                    </div>
                {% endif %}
              {% endfor %}
        <div class="list-group">
            {% for cart in carts %}
                {% if cart.item2 == None %}
                <div class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                    <a href="{% url 'App_Order:remove' pk=cart.item.pk %}">
                        <img src="https://www.seekpng.com/png/detail/97-970602_trash-garbage-recycle-bin-svg-png-icon-free.png" alt="twbs" width="20" height="20" class="rounded-circle flex-shrink-0">
                    </a>
                    <div class="d-flex gap-2 w-100 justify-content-between">
                      <div class="col-md-6">
                        <h6 class="mb-0">{{cart.item.gift_name}}</h6>
                      </div>
                      <div class="col-md-3" style="width: 40%;">
                       <a class="plus-btn" href="{% url 'App_Order:decrease' pk=cart.item.pk %}">
                                            <i class="icofont-minus-circle"></i>
                                          </a>
                                           <b>{{ cart.quantity }}</b>
                                          <a class="minus-btn" href="{% url 'App_Order:increase' pk=cart.item.pk %}">
                                            <i class="icofont-plus-circle"></i>
                                          </a>
                      </div>
                      <div>
                        <h6 class="mb-0">
                            <b> {{ cart.quantity }} X £{{cart.item.gift_price}} = {{ cart.get_total }}</b>
                        </h6>
                      </div>
                    </div>
                </div>
                {% else %}
                 <div class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <a href="{% url 'App_Order:item_remove' pk=cart.item2.pk %}">
                <img src="https://www.seekpng.com/png/detail/97-970602_trash-garbage-recycle-bin-svg-png-icon-free.png" alt="twbs" width="20" height="20" class="rounded-circle flex-shrink-0">
            </a>
            <div class="d-flex gap-2 w-100 justify-content-between">
              <div class="col-md-6">
                <h6 class="mb-0">{{cart.item2.item_name}}</h6>
              </div>
              <div class="col-md-3" style="width: 40%;">
                <a class="plus-btn" href="{% url 'App_Order:item_decrease' pk=cart.item2.pk %}">
                               <i class="icofont-minus-circle"></i>
                              </a>
                                 <b>{{ cart.quantity }}</b>
                              <a class="minus-btn" href="{% url 'App_Order:item_increase' pk=cart.item2.pk %}">
                                <i class="icofont-plus-circle"></i>
                              </a>
              </div>
              <div>
                <h6 class="mb-0">
                    <b> {{ cart.quantity }} X £{{cart.item2.item_price}} = {{ cart.get_total }}</b>
                </h6>
              </div>
            </div>
          </div>
                {% endif %}
            {% endfor %}
         <div class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <div class="d-flex gap-2 w-100 justify-content-between">
              <div class="col-md-8">
                <h6 class="mb-0">Total</h6>
              </div>
              <div>
                <h6 class="mb-0">
                    <b> £{{order.get_totals | floatformat:2 }} </b>
                </h6>
              </div>
            </div>
          </div>
        <div class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <div class="d-flex gap-2 w-100 justify-content-between">
              <div class="col-md-8 col-sm-12">
                  <a href="{% url 'App_Lakshabay:onlineorder' %}" class="btn btn-warning mr-4">Continue Shoping</a>
              </div>
              <div class="col-md-8 col-sm-12">
                <a href="{% url 'App_Payment:checkout' %}" class="btn btn-success mr-4">Proceed To Checkout</a>
              </div>

            </div>
          </div>
        </div>
    </div>
    </section>

{% endblock %}