App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name="cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),

    path('add-food/<pk>/', views.item_add_to_cart, name="item_ad"),
    path('item-cart/', views.item_cart_view, name="item_cart"),
    path('item-increase/<pk>/', views.itemincrease_cart, name="item_increase"),
    path('item-decrease/<pk>/', views.itemdecrease_cart, name="item_decrease"),
    path('item-remove/<pk>/', views.itemremove_from_cart, name="item_remove"),


]

App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = "App_Payment"
from App_Payment.views import (
    CreateCheckoutSessionView
)
urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('payment/<int:id>',views.PaymentView,name='payment'),
    path('cancel/', views.CancelView, name='cancel'),
    path('success/', views.SuccessView, name='success'),
    path('create-checkout-session/<pk>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),

]

lakshabay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Lakshabay.urls')),
    path('', include('App_Order.urls')),
    path('', include('App_Payment.urls')),
    path('superadmin/',include('App_Superadmin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

App_Payment/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class BillingAddress(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    company = models.CharField(max_length=100)
    country = models.CharField(max_length=50)
    address = models.CharField(max_length=264)
    address2 = models.CharField(max_length=265,blank=True)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    zipcode = models.CharField(max_length=10)
    phone = models.CharField(max_length=15)
    aditional_info = models.TextField(blank=True, default="additional information")

    def __str__(self):
        return f'{self.firstname} billing address'

    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]

        for field_name in field_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True

    class Meta:
        verbose_name_plural = "Billing Addresses"

App_Payment/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from App_Payment.models import *

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class BillingForm(forms.ModelForm):
    firstname=forms.CharField(max_length=50,label="First Name")
    lastname=forms.CharField(max_length=50,label="Last Name")
    company=forms.CharField(max_length=50,label="Company")
    country=forms.CharField(max_length=50,label="Country")
    address=forms.CharField(max_length=50,label="Address")
    address2=forms.CharField(max_length=50,label="Address 2")
    city=forms.CharField(max_length=50,label="City")
    state=forms.CharField(max_length=50,label="State")
    zipcode=forms.IntegerField(label="Zipcode")
    phone=forms.IntegerField(label="Phone")
    aditional_info = forms.CharField(label="Additional Informatio (optional)",required=False,widget=forms.Textarea(attrs={
        'class': 'form-control',
        'rows': 3,
        'cols': 40,
        'padding': '10px',
        'placeholder': "Enter  your Text here",
    }))
    class Meta:
        model=BillingAddress
        fields=('firstname','lastname','company','country','address','address2','city','state','zipcode','phone','aditional_info')

App_Payment/views.py
from decimal import Decimal
import socket

from django.contrib.auth import authenticate, login
from django.http import JsonResponse, HttpResponseNotFound
from django.views.decorators.csrf import csrf_exempt
import stripe
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.views import View
from App_Payment.forms import SignUpForm,BillingForm
from lakshabay import settings
from App_Lakshabay.models import *
from App_Order.models import *
from App_Lakshabay.views import getcart,getorder

stripe.api_key = settings.STRIPE_SECRET_KEY
def checkout(request):
    if request.user.is_authenticated:
        try:
            orders = Order.objects.filter(user=request.user, ordered=False).latest('id')
        except:
            orders=None
        print(orders.ordered)
        if request.method=="POST":
            f_name=request.POST.get('firstname')
            l_name=request.POST.get('lastname')
            c_name=request.POST.get('company')
            cn_name=request.POST.get('country')
            ad=request.POST.get('address_1')
            ad2=request.POST.get('address_2')
            city=request.POST.get('city')
            sate=request.POST.get('state')
            zip=request.POST.get('zipcode')
            ph=request.POST.get('phone')
            adi=request.POST.get('additional_info')

            billing=BillingAddress()
            billing.firstname=f_name
            billing.lastname=l_name
            billing.country=cn_name
            billing.company=c_name
            billing.address=ad
            billing.address2=ad2
            billing.city=city
            billing.state=sate
            billing.zipcode=zip
            billing.phone=ph
            billing.aditional_info=adi
            billing.save()
            orders.billing_address=billing
            orders.save()
            return redirect(orders.get_absolute_url())
        else:
            context = {
                'carts': getcart(request),
                'order': getorder(request),
                'orders_not_null':orders,
            }
            return render(request, 'App_Payment/checkout.html', context)
    else:
        if request.method=="POST":
            form=SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                my_order = TempCart.objects.filter(user_id=request.session['user_id'], purchased=False)
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                for i in my_order:
                    if i.item2 == None:
                        new_cart = Cart.objects.create(
                            user=request.user, item=i.item, quantity=i.quantity
                        )
                        new_cart.save()
                    else:
                        new_cart = Cart.objects.create(
                            user=request.user, item2=i.item2, quantity=i.quantity
                        )
                        new_cart.save()
                print("ordered")
                ord = Order.objects.create(
                    user=request.user, ordered=False
                )
                ord.save()
                ord = Order.objects.get(user=request.user, ordered=False)
                cart_list = Cart.objects.filter(user=request.user)
                for i in cart_list:
                    ord.orderitems.add(i)
                ord.save()
                for i in cart_list:
                    i.purchased = True
                    i.save()
                return redirect('App_Payment:checkout')
        else:
            form=SignUpForm()
        context = {
            'carts': getcart(request),
            'order': getorder(request),
            'stripe':settings.STRIPE_PUBLISHABLE_KEY,
            'form':form,
        }
        return render(request, 'App_Payment/checkout.html', context)


def PaymentView(request,id):
    msg=None
    if Order.objects.filter(id=id).exists():
        order=Order.objects.get(id=id)
    else:
        msg="Your Order id is invalid"
    context={
        'msg':msg,
        'orders':order,
        'carts': getcart(request),
        'order': getorder(request),
        'stripe': settings.STRIPE_PUBLISHABLE_KEY
    }
    return render(request,'App_Payment/payment.html',context)


stripe.api_key = settings.STRIPE_SECRET_KEY
class CreateCheckoutSessionView(View):
    def post(self, request, *args, **kwargs):
        product_id = self.kwargs["pk"]
        donate = Order.objects.get(id=product_id)
        title="Order ID :"+str(donate.id)
        YOUR_DOMAIN = "http://54.227.68.244:8777"
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[
                {
                    'price_data': {
                        'currency': 'gbp',
                        'unit_amount':int(donate.get_totals()*100),
                        'product_data': {
                            'name': title
                        },
                    },
                    'quantity': 1,
                },
            ],
            metadata={
                "product_id": 12
            },
            mode='payment',
            success_url=request.build_absolute_uri(
            reverse('App_Payment:success')
        ) + "?session_id={CHECKOUT_SESSION_ID}",
            cancel_url=request.build_absolute_uri(reverse('App_Payment:cancel')),
        )
        donate.paymentId = checkout_session['payment_intent']
        donate.save()

        return JsonResponse({
            'id': checkout_session.id
        })


def SuccessView(request):
    session_id = request.GET.get('session_id')
    if session_id is None:
        return HttpResponseNotFound()
    stripe.api_key = settings.STRIPE_SECRET_KEY
    session = stripe.checkout.Session.retrieve(session_id)
    ord = get_object_or_404(Order, paymentId=session.payment_intent)
    ord.ordered=True
    ord.save()
    for i in ord.orderitems.all():
        i.purchased = True
        i.save()

    context = {
        'carts': getcart(request),
        'order': getorder(request),
    }
    return render(request,'App_Payment/success.html',context)



def CancelView(request):
    context = {
        'carts': getcart(request),
        'order': getorder(request),
    }
    return render(request,'App_Payment/cancel.html',context)

templates/App_Payment/cancel.html
{% extends 'App_Lakshabay/base.html' %}
{% load static %}
{% block content %}
            <section  id="menu" class="menu-area ptb-100">
                <div class="container">
                    <div class="section-title">
                        <span>Failed Page</span>
                    </div>
                    <div class="alert alert-danger" role="alert">
<h4 class="alert-heading">Failed</h4>
  <p>Something went wrong, your payment is not completed . Please try again to complete your payment.</p>
</div>

                </div>
                <div class="line-bg">
                    <img src="{% static 'assets/img/line.png' %}" alt="line" /></div>
            </section>
{% endblock %}

templates/App_Payment/complete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="5; url={% url 'App_Shop:home' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Payment Status</title>
</head>
<body>
  <div class="container">
    <div class="messages container mt-2">
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</body>
</html>

templates/App_Payment/confirmation.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
 
    <br><br> <br>   <br><br> <br>
   <h1 style="color: blue;" class="text-center">Your Response Has Been Recorded. Thanks a lot!</h1>
      <br><br> <br>   <br><br> <br>
 
</div>
{% endblock %}

templates/App_Payment/order.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container mt-5">
  <h2 class="text-center"><strong>Your Orders</strong></h2>
  <div class="row">
    <div class="col-md-12">
      <div class="card mt-5" style="height:auto">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Order Id</th>
                <th scope="col">Products</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="#">{{ order.orderId }}</a></td>
                <td>
                  {% for item in order.orderitems.all %} {{item}} <br> {% endfor %}
                </td>
                <td><span class="badge badge-primary">Processing Your ORder</span></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-12 my-5 text-center">
      <a href="{% url 'App_Shop:home' %}">Bact to Home</a>
    </div>
  </div>
</div>
{% endblock %}

templates/App_Payment/payment.html
{% extends 'App_Lakshabay/base.html' %}
{% load static %}
{% block content %}
    <style>
        .cart-btn{
                background: #ffffff;
    padding: 2px 6px;
    border-radius: 5px;
    text-decoration: none;
    color: #000000;
        }
    .shopping-cart {
  width: 750px;
  height: auto;
  margin: 80px auto;
  background: #FFFFFF;
  box-shadow: 1px 2px 3px 0px rgba(0,0,0,0.10);
  border-radius: 6px;
  display: flex;
  flex-direction: column;
}
    .title {
  height: 60px;
  border-bottom: 1px solid #E1E8EE;
  padding: 20px 30px;
  color: #5E6977;
  font-size: 18px;
  font-weight: 400;
}

.item {
  padding: 20px 30px;
  height: 120px;
  display: flex;
}

.item:nth-child(20) {
  border-top:  1px solid #E1E8EE;
  border-bottom:  1px solid #E1E8EE;
}
    .buttons {
  position: relative;
  padding-top: 30px;
  margin-right: 60px;
}
@keyframes animate {
  0%   { background-position: left;  }
  50%  { background-position: right; }
  100% { background-position: right; }
}

.description {
  padding-top: 15px;
  margin:0 auto;
  width: 115px;
}

.description span {
  display: block;
  font-size: 14px;
  color: #43484D;
  font-weight: 400;
}

.description span:first-child {
  margin-bottom: 5px;
}
.description span:last-child {
  font-weight: 300;
  margin-top: 8px;
  color: #86939E;
}
    .quantity {
  padding-top: 20px;
  margin-right: 60px;
}
.quantity input {
  -webkit-appearance: none;
  border: none;
  text-align: center;
  width: 32px;
  font-size: 16px;
  color: #43484D;
  font-weight: 300;
}

button[class*=btn] {
  width: 30px;
  height: 30px;
  background-color: #E1E8EE;
  border-radius: 6px;
  border: none;
  cursor: pointer;
}
.minus-btn img {
  margin-bottom: 3px;
}
.plus-btn img {
  margin-top: 2px;
}

button:focus,
input:focus {
  outline:0;
}
.total-price {
  width: 83px;
  padding-top: 21px;
  text-align: center;
  font-size: 16px;
  color: #43484D;
  font-weight: 300;
}
@media (max-width: 800px) {
  .shopping-cart {
    width: 100%;
    height: auto;
    overflow: hidden;
  }
  .item {
    height: auto;
    flex-wrap: wrap;
    justify-content: center;
  }
  .image img {
    width: 50%;
  }
  .image,
  .quantity,
  .description {
    width: 100%;
    text-align: center;
    margin: 6px 0;
  }
  .buttons {
    margin-right: 20px;
  }
}
</style>
            <section  id="menu" class="menu-area ptb-100">
                <div class="container">
                    <div class="section-title">
                        <span>Discover</span>
                        <h2>Your Order Information</h2>
                    </div>
                {% if msg %}
                <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<div class="alert alert-primary d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
  <div>
    {{ msg }}
  </div>
</div>
                {% else %}
                    <div class="row g-5">
                      <div class="col-md-5 col-lg-5 order-md-last">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                          <span class="text-primary">Your Order</span>
                        </h4> <hr class="my-4">
                           <div class="list-group">
                    {% for cart in orders.orderitems.all %}
                        {% if cart.item2 == None %}
                        <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                            <img src="{{ cart.item.gift_image.url }}" alt="twbs" width="32" height="32" class="rounded-circle flex-shrink-0">
                            <div class="d-flex gap-2 w-100 justify-content-between">
                              <div>
                                <h6 class="mb-0">{{cart.item.gift_name}}</h6>
                                <p class="mb-0 opacity-75">{{ cart.quantity }} X £{{cart.item.gift_price}}</p>
                              </div>
                              <h4 class="opacity-50 text-nowrap">£{{ cart.get_total }}</h4>
                            </div>
                          </a>
                        {% else %}
                        <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                            <img src="{{ cart.item2.photo.url }}" alt="twbs" width="32" height="32" class="rounded-circle flex-shrink-0">
                            <div class="d-flex gap-2 w-100 justify-content-between">
                              <div>
                                <h6 class="mb-0">{{cart.item2.item_name}}</h6>
                                <p class="mb-0 opacity-75">{{ cart.quantity }} X  £{{cart.item2.item_price}}</p>
                              </div>
                              <h4 class="opacity-50 text-nowrap">£{{ cart.get_total }}</h4>
                            </div>
                          </a>
                        {% endif %}
                    {% endfor %}
                    <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                            <div class="d-flex gap-2 w-100 justify-content-between">
                              <div>
                                <h6 class="mb-0">Total :</h6>
                                <p class="mb-0 opacity-75"></p>
                              </div>
                              <h2 class="opacity-50 text-nowrap">£{{ orders.get_totals }}</h2>
                            </div>
                          </a>
                    </div>
                      </div>
                      <div class="col-md-7 col-lg-7">
                        <h4 class="mb-3">Your Billing address</h4>
                           <hr class="my-4">
                        <div class="needs-validation">
                          <div class="row g-3">
                            <div class="list-group">
                              <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                                <div class="row d-flex gap-2 w-100 justify-content-between">
                                  <div class="col">
                                    <h6 class="col mb-0">First Name : {{ orders.billing_address.firstname }} </h6>
                                  </div>
                                  <div class="col">
                                    <h6 class="col mb-0">Last Name  : {{ orders.billing_address.firstname }} </h6>
                                  </div>
                                </div>
                              </a>
                              <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                                <div class="row d-flex gap-2 w-100 justify-content-between">
                                  <div class="col">
                                    <h6 class="col mb-0">Company : {{ orders.billing_address.company }}</h6>
                                  </div>
                                  <div class="col">
                                    <h6 class="col mb-0">Country : {{ orders.billing_address.country }} </h6>
                                  </div>
                                </div>
                              </a>
                                <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                                <div class="row d-flex gap-2 w-100 justify-content-between">
                                  <div class="col">
                                    <h6 class="col mb-0">City : {{ orders.billing_address.city }}</h6>
                                  </div>
                                  <div class="col">
                                    <h6 class="col mb-0">State : {{ orders.billing_address.state }} </h6>
                                  </div>
                                </div>
                              </a>
                               <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                                <div class="row d-flex gap-2 w-100 justify-content-between">
                                  <div class="col">
                                    <h6 class="col mb-0">Zipcode : {{ orders.billing_address.zipcode }}</h6>
                                  </div>
                                  <div class="col">
                                    <h6 class="col mb-0">Phone : {{ orders.billing_address.phone }} </h6>
                                  </div>
                                </div>
                              </a>
                                 <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                                <div class="row d-flex gap-2 w-100 justify-content-between">
                                  <div class="col">
                                    <h6 class="col mb-0">Address : {{ orders.billing_address.address }} {{ orders.billing_address.address2 }}</h6>
                                  </div>
                                </div>
                              </a>
                              <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                                <div class="row d-flex gap-2 w-100 justify-content-between">
                                  <div class="col">
                                    <h6 class="col mb-0">Additional Info : {{ orders.billing_address.aditional_info }}</h6>
                                  </div>
                                </div>
                              </a>
                            </div>
                          </div>
                          <div class="my-3">
                            <div class="form-check">
                              <span class="mb-3">We Accept :</span>
                              <img src="{% static 'visa.svg' %}" width="50" height="50">
                              <img src="{% static 'mastercard.svg' %}" width="50" height="50">
                              <img src="{% static 'stripe.svg' %}" width="50" height="50">
                            </div>
                          </div>
                        </div>
                        <button class="w-auto my-2 btn" id="checkout-button" type="button" style="padding: 7px 15px;background: #000000;color: #ffffff;">Pay Now</button>
                      </div>
                    </div>
                {% endif %}

                </div>
                <div class="line-bg">
                    <img src="{% static 'assets/img/line.png' %}" alt="line" /></div>
            </section>
 {% csrf_token %}
<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
                                    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                                    var stripe = Stripe("{{ stripe }}");
                                    var checkoutButton = document.getElementById("checkout-button");
                                    checkoutButton.addEventListener("click", function () {
                                      fetch("{% url 'App_Payment:create-checkout-session' orders.id %}", {
                                        method: "POST",
                                        headers: {
                                            'X-CSRFToken': csrftoken
                                        }
                                      })
                                        .then(function (response) {
                                          return response.json();
                                        })
                                        .then(function (session) {
                                          return stripe.redirectToCheckout({ sessionId: session.id });
                                        })
                                        .then(function (result) {
                                          // If redirectToCheckout fails due to a browser or network
                                          // error, you should display the localized error message to your
                                          // customer using error.message.
                                          if (result.error) {
                                            alert(result.error.message);
                                          }
                                        })
                                        .catch(function (error) {
                                          console.error("Error:", error);
                                        });
                                    });
                                  </script>
{% endblock %}

templates/App_Payment/success.html
{% extends 'App_Lakshabay/base.html' %}
{% load static %}
{% block content %}
            <section  id="menu" class="menu-area ptb-100">
                <div class="container">
                    <div class="section-title">
                        <span>Success Page</span>
                    </div>
                    <div class="alert alert-success" role="alert">
                          <h4 class="alert-heading">Well Done!</h4>
  <p>You have successfully completed your payment.</p>
</div>

                </div>
                <div class="line-bg">
                    <img src="{% static 'assets/img/line.png' %}" alt="line" /></div>
            </section>
{% endblock %}